# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus:
google_analytics: UA-92230923-1
timezone:          Asia/Saigon
title: The Best Coder Blog
description: This is a blog about website and mobile development, some mathematics, and the occasional philosophy. Not necessarily in that order.
keywords: "Software Engineering, Mathematics, Philosophy, Scala, Epistemology, Existentialism, Programming, Machine-Learning, Artificial Intelligence, Statistics, Probability, Puzzles, Website Development, Mobile Development"
url: https://bestcoder.info   # with the https protocol
enforce_ssl: www.bestcoder.info

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: The Best Coder Blog

author:
  name: Quan Nguyen
  email: quannguyen@bestcoder.info
  github: minhquan4080
  twitter: libraQmn
  pinterest:
  linkedin: quanmnlibra
  bio: I'm a Ruby on Rails developer. But I can work same as a Full-stack developer. A spirit of learning new technologies. Sense of responsibility, carefulness in all the works done are my greatest strengths.
  email_md5: 63d3b6ee006fd7c195170b07b3082ee5

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
