# Site
name: "The Best Coder Blog"
description: "тнιs ιs ᴀ ʙʟoԍ ᴀʙouт wᴇʙsιтᴇ ᴀɴᴅ мoʙιʟᴇ ᴅᴇvᴇʟoᴘмᴇɴт, soмᴇ мᴀтнᴇмᴀтιcs, ᴀɴᴅ тнᴇ occᴀsιoɴᴀʟ ᴘнιʟosoᴘнʏ. ɴoт ɴᴇcᴇssᴀʀιʟʏ ιɴ тнᴀт oʀᴅᴇʀ - ｄｅｒｅｋ ."
meta_description: "This is a blog about website and mobile development, some mathematics, and the occasional philosophy. Not necessarily in that order"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
google_analytics: 'UA-92230923-1'
disqus: 'bestcoderdotinfo'
mailchimp-list: ''
url: "https://blog.dereknguyen.xyz"
enforce_ssl: www.blog.dereknguyen.xyz

# Authors
authors:
  derek:
    name: ｄｅｒｅｋ
    display_name: ｄｅｒｅｋ
    gravatar: 63d3b6ee006fd7c195170b07b3082ee5
    email: quannguyen@bestcoder.info
    web: https://cv.dereknguyen.xyz
    twitter: https://twitter.com/libraQmn
    description: "Software Engineer strong background Ruby on Rails. Also, interest Java Script, Go, PHP and Blockchain."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge
